Add `/api/v1/entity-relationship-tree/` endpoint
fga-eps-mds/2022-1-MeasureSoftGram-Service pull request #13
Opened 2022-08-10 01:20 UTC by durvalcarvalho

Adiciona o endpoint que irá listar todos os dados necessários para renderizar os filtros do novo componente do dashboard.

![image](https://user-images.githubusercontent.com/31013187/183789598-cc977e3c-6a8a-451d-99a2-adbcb7091fad.png)

2022-08-14 00:56 UTC, herickport requested changes

2022-08-14 00:56 UTC, herickport commented on src/service/sub_serializers/entity_tree.py
> +        model = models.SupportedCharacteristic
Acredito que aqui o correto seria `SupportedSubCharacteristic`

2022-08-14 00:56 UTC, herickport commented on src/service/sub_serializers/entity_tree.py
> +    def get_measures(self, obj: models.SupportedCharacteristic):
Acredito que aqui o correto seria `SupportedSubCharacteristic`

2022-08-14 01:08 UTC, herickport commented
@durvalcarvalho 
A implementação do endpoint que lista a árvore de entidades ficou mto boa, no entanto ela lista todas as entidades suportadas pelo sistema, independente da pré-configuração. O @LeoSilvaGomes pode confirmar melhor, mas acredito que um dos requisitos para a listagem dos filtros no dashboard seja que ele apresente apenas o que o usuário tenha selecionado na pré-configuração, o que não é possível com esse endpoint atual.

De qualquer forma, acredito que esse seja um enpoint útil para o projeto e caso seja realmente necessário retornar apenas o que foi definido na pré-configuração, podemos criar outra tarefa.

2022-08-15 17:23 UTC, durvalcarvalho commented on src/service/sub_serializers/entity_tree.py
> +        model = models.SupportedCharacteristic
Bem observado!

2022-08-15 17:23 UTC, durvalcarvalho commented on src/service/sub_serializers/entity_tree.py
> +    def get_measures(self, obj: models.SupportedCharacteristic):
Bem observado!

2022-08-15 18:29 UTC, durvalcarvalho commented
> @durvalcarvalho A implementação do endpoint que lista a árvore de entidades ficou mto boa, no entanto ela lista todas as entidades suportadas pelo sistema, independente da pré-configuração. O @LeoSilvaGomes pode confirmar melhor, mas acredito que um dos requisitos para a listagem dos filtros no dashboard seja que ele apresente apenas o que o usuário tenha selecionado na pré-configuração, o que não é possível com esse endpoint atual.
> 
> De qualquer forma, acredito que esse seja um enpoint útil para o projeto e caso seja realmente necessário retornar apenas o que foi definido na pré-configuração, podemos criar outra tarefa.

Realmente! Eu pensei novamente sobre essa funcionalidade e criei o endpoint que retorna a mesma árvore de dependência das entidades, mas levando em consideração a pré-configuração vigente. 

`GET` `/api/v1/organizations/1/repository/1/entity-relationship-tree/`

2022-08-15 18:32 UTC, merged

2022-08-15 18:33 UTC, durvalcarvalho commented
@LeoSilvaGomes 
Os endpoints necessários para essa nova funcionalidade estão disponíveis no ambiente do heroku