#240 optimizes queries
fga-eps-mds/2022-1-MeasureSoftGram-Service pull request #15
Opened 2022-08-10 21:39 UTC by durvalcarvalho

## Descrição

Otimiza várias queries para diminuir o número de consultas no banco de dados

2022-08-14 02:14 UTC, herickport requested changes
@durvalcarvalho 
Muito massa a ideia do CachedManager. Só tá rolando um problema na comparação dos filtros da requisição anterior com a atual que acabou "quebrando" as requisições de cálculo de entidades. Detalhei melhor o problema no comentário do review abaixo. Arrumando isso fica show.

2022-08-14 02:14 UTC, herickport commented on src/service/managers.py
> +        if is_the_same_call(call, CachedManager.last_call):
Os parâmetros da função estão invertidos

2022-08-14 02:14 UTC, herickport commented on src/service/managers.py
> +        set(prev_call['kwargs']) == set(current_call['kwargs'])
Esse set tá pegando e comparando apenas as chaves do dicionário `kwargs`, então se você compara:

```python
set({'key__in': {'passed_tests'}}) == set({'key__in': {'passed_tests', 'test_builds'}})
```

ele retorna `True`, pois a comparação que está sendo feita é:

```python
{'key__in'} == {'key__in'}
```

Isso tá ocasionando erro nas requisições de cálculo das entidades. Nas medidas, por exemplo, ao solicitar o cálculo de novas medidas (adicionar `keys` no JSON), ele considera que a requisição é a mesma da anterior e com isso retorna `404` falando que as medidas adicionadas não são suportadas, mesmo se tratando de medidas válidas. O problema também ocorre ao retirar medidas do cálculo, pois por achar que é a mesma requisição, ele retorna as medidas solicitadas na requisição anterior.

2022-08-15 20:12 UTC, durvalcarvalho commented on src/service/managers.py
> +        set(prev_call['kwargs']) == set(current_call['kwargs'])
Muito bem observado!

2022-08-15 20:15 UTC, merged