#134 - Add ci feedback time measure
fga-eps-mds/2022-1-MeasureSoftGram-Service pull request #8
Opened 2022-08-01 01:47 UTC by heronsousa

## Descrição
Adiciona nova medida CI Feedback Time.

 - Adiciona medida como uma medida suportada
 - Ajustes para obter a medida pela chave 

Closes #134

2022-08-01 12:47 UTC, durvalcarvalho requested changes
@heronsousa 

O seu PR está desfazendo uma funcionalidade que foi validada com o Usuário. 

Existe um motivo para o nome dessas métricas serem dinâmicas. Tente tratar a particularidade do seu caso à parte sem desfazer o trabalho já realizado.

2022-08-01 14:30 UTC, heronsousa commented
> @heronsousa
> 
> O seu PR está desfazendo uma funcionalidade que foi validada com o Usuário.
> 
> Existe um motivo para o nome dessas métricas serem dinâmicas. Tente tratar a particularidade do seu caso à parte sem desfazer o trabalho já realizado.

Vou procurar uma outra solução. No core tenho que definir o schema com as chaves das métricas, alguma sugestão para lidar  com essas chaves dinamicas no schema?

2022-08-01 15:49 UTC, durvalcarvalho commented
> > @heronsousa
> > O seu PR está desfazendo uma funcionalidade que foi validada com o Usuário.
> > Existe um motivo para o nome dessas métricas serem dinâmicas. Tente tratar a particularidade do seu caso à parte sem desfazer o trabalho já realizado.
> 
> @durvalcarvalho Vou procurar uma outra solução. No core tenho que definir o schema com as chaves das métricas, alguma sugestão para lidar com essas chaves dinamicas no schema?

Minha sugestão é modificar a [linha que obtém o nome da métrica](https://github.com/fga-eps-mds/2022-1-MeasureSoftGram-Service/blob/develop/src/service/sub_models/measures.py#L46). 

A lógica seria:
- 1. Identificar que é o nome de uma métrica que precisa de tratamento.
- 2. Tratar o nome, substituindo a parte dinâmica pela parte genérica 
  - (algo do tipo `metric_name.split(' in the last')[0] + " in the last X days"`

2022-08-03 11:54 UTC, durvalcarvalho requested changes

2022-08-03 11:54 UTC, durvalcarvalho commented on src/config/settings.py
> +<<<<<<< HEAD
Esse Pull Request possui conflitos não resolvidos.

![image](https://user-images.githubusercontent.com/31013187/182601421-23b6edcf-41d2-4f00-ad3a-d473ec6c44d4.png)

![image](https://user-images.githubusercontent.com/31013187/182601477-77dc2d06-8952-4827-8e51-42c3eeec58b9.png)

![image](https://user-images.githubusercontent.com/31013187/182601535-987baf32-12cd-48e1-8e6e-77a84398a7dc.png)

2022-08-03 12:44 UTC, merged